-- =====================================================================
-- Autowagen Master — EPC — Multiple Types for **every** subcategory
--
-- Adds ~5 real **Types** (Level 3) per subcategory (Engine through Accessories).
-- Uses a temporary seed table + join on `epc_categories.slug` + `epc_subcategories.slug`.
-- Temp columns use **utf8mb4_unicode_ci** (same as `02_epc.sql`) so MySQL 8 does not throw
-- **#1267 Illegal mix of collations** (utf8mb4_0900_ai_ci vs utf8mb4_unicode_ci) on `slug = slug`.
-- **ON DUPLICATE KEY UPDATE** on (`subcategory_id`,`slug`) → safe re-run.
--
-- **After this file**, run again in order (extends spine for new types):
--   1) `sql/02d_epc_spine_step3.sql`
--   2) `sql/02e_epc_variants_dismantler.sql`  (optional)
--
-- Also compatible with `02f` (doors): duplicate slugs merge cleanly.
-- =====================================================================

DROP TEMPORARY TABLE IF EXISTS `epc_type_seed`;
CREATE TEMPORARY TABLE `epc_type_seed` (
  `cat_slug`    VARCHAR(80)  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `sub_slug`    VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `name`        VARCHAR(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `slug`        VARCHAR(180) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `sort_order`  INT          NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `epc_type_seed` (`cat_slug`, `sub_slug`, `name`, `slug`, `sort_order`) VALUES
-- --- Engine (new 02c subs) -------------------------------------------
('engine','engine-block-internals','Crankshaft & bearings','crankshaft-bearings',20),
('engine','engine-block-internals','Pistons & connecting rods','pistons-rods',30),
('engine','engine-block-internals','Cylinder block & liners','block-liners',40),
('engine','engine-block-internals','Sump & oil control','sump-oil-control',50),
('engine','engine-block-internals','Complete short block','short-block-complete',60),
('engine','cylinder-head-valvetrain','Cylinder head (bare)','head-bare',20),
('engine','cylinder-head-valvetrain','Valves & springs','valves-springs',30),
('engine','cylinder-head-valvetrain','Camshaft & followers','camshaft-followers',40),
('engine','cylinder-head-valvetrain','Rocker gear','rocker-gear',50),
('engine','cylinder-head-valvetrain','Complete cylinder head','head-complete',60),
('engine','intake-exhaust-engine','Inlet manifold','inlet-manifold',20),
('engine','intake-exhaust-engine','Exhaust manifold','exhaust-manifold-engine',30),
('engine','intake-exhaust-engine','Throttle body & ducting','throttle-ducting',40),
('engine','intake-exhaust-engine','EGR & flaps','egr-flaps',50),
('engine','intake-exhaust-engine','Studs & gaskets (int/exh)','intexh-gaskets',60),
('engine','forced-induction','Turbocharger','turbocharger',20),
('engine','forced-induction','Supercharger','supercharger',30),
('engine','forced-induction','Intercooler & piping','intercooler-piping',40),
('engine','forced-induction','Boost control & dump valve','boost-control-bov',50),
('engine','forced-induction','Complete FI kit (as removed)','fi-kit-complete',60),
('engine','engine-electrics-starter-alt','Starter motor','starter-motor',20),
('engine','engine-electrics-starter-alt','Alternator','alternator',30),
('engine','engine-electrics-starter-alt','Ignition coils & plugs','ignition-coils-plugs',40),
('engine','engine-electrics-starter-alt','Engine sensors (misc)','engine-sensors-misc',50),
('engine','engine-electrics-starter-alt','Engine bay wiring','engine-bay-wiring',60),
('engine','timing-belts-chains','Timing belt kit','timing-belt-kit',20),
('engine','timing-belts-chains','Timing chain kit','timing-chain-kit',30),
('engine','timing-belts-chains','Tensioners & guides','timing-tensioners',40),
('engine','timing-belts-chains','Sprockets & gears','timing-sprockets',50),
('engine','timing-belts-chains','Complete timing service set','timing-set-complete',60),
('engine','engine-mounts-dampers','LH engine mount','eng-mount-lh',20),
('engine','engine-mounts-dampers','RH engine mount','eng-mount-rh',30),
('engine','engine-mounts-dampers','Torque rod / dog bone','torque-rod-dogbone',40),
('engine','engine-mounts-dampers','Subframe / cradle (engine)','eng-subframe-cradle',50),
('engine','engine-mounts-dampers','Mount hardware set','mount-hardware-set',60),
-- Petrol & Diesel (seed subs)
('engine','petrol','Turbocharged petrol','turbo-petrol',30),
('engine','petrol','Naturally aspirated petrol','na-petrol',40),
('engine','petrol','Complete engine assembly','petrol-engine-complete',50),
('engine','diesel','Injectors & rails','diesel-injectors',20),
('engine','diesel','High-pressure fuel pump','diesel-hp-pump',30),
('engine','diesel','Turbocharger (diesel)','diesel-turbo',40),
('engine','diesel','EGR / intake (diesel)','diesel-egr-intake',50),
('engine','diesel','Complete diesel engine','diesel-engine-complete',60),
-- Transmission & driveline -------------------------------------------
('transmission-driveline','manual-gearbox','5-speed assembly','mg-5-speed',20),
('transmission-driveline','manual-gearbox','6-speed assembly','mg-6-speed',30),
('transmission-driveline','manual-gearbox','7-speed / O/D unit','mg-7-od',40),
('transmission-driveline','manual-gearbox','Selector & linkage','mg-selector-linkage',50),
('transmission-driveline','manual-gearbox','Housing & casings','mg-housing',60),
('transmission-driveline','manual-gearbox','Complete manual gearbox','mg-complete',70),
('transmission-driveline','automatic-gearbox','Torque converter','ag-torque-converter',20),
('transmission-driveline','automatic-gearbox','Valve body','ag-valve-body',30),
('transmission-driveline','automatic-gearbox','Mechatronics / control unit','ag-mechatronics',40),
('transmission-driveline','automatic-gearbox','Oil pan & filter (auto)','ag-oil-pan',50),
('transmission-driveline','automatic-gearbox','Planet / clutch packs (as removed)','ag-internals',60),
('transmission-driveline','automatic-gearbox','Complete automatic gearbox','ag-complete',70),
('transmission-driveline','clutch-flywheel','Clutch disc','clutch-disc',20),
('transmission-driveline','clutch-flywheel','Pressure plate','clutch-pressure-plate',30),
('transmission-driveline','clutch-flywheel','Release bearing / CSC','clutch-release-bearing',40),
('transmission-driveline','clutch-flywheel','Flywheel / flexplate','flywheel-flexplate',50),
('transmission-driveline','clutch-flywheel','Master & slave cylinder','clutch-hydraulics',60),
('transmission-driveline','clutch-flywheel','Complete clutch kit','clutch-kit-complete',70),
('transmission-driveline','propeller-shaft','Front shaft section','propshaft-front',20),
('transmission-driveline','propeller-shaft','Centre bearing','propshaft-centre-bearing',30),
('transmission-driveline','propeller-shaft','Rear shaft section','propshaft-rear',40),
('transmission-driveline','propeller-shaft','U-joints / couplings','propshaft-ujoints',50),
('transmission-driveline','propeller-shaft','Complete propshaft','propshaft-complete',60),
('transmission-driveline','differential-final-drive','Crown wheel & pinion','diff-cwp',20),
('transmission-driveline','differential-final-drive','Carrier & LSD unit','diff-carrier-lsd',30),
('transmission-driveline','differential-final-drive','Axle bearings & seals','diff-bearings-seals',40),
('transmission-driveline','differential-final-drive','Diff cover & breather','diff-cover',50),
('transmission-driveline','differential-final-drive','Complete differential','diff-complete',60),
('transmission-driveline','half-shafts-cv-joints','LH half-shaft','halfshaft-lh',20),
('transmission-driveline','half-shafts-cv-joints','RH half-shaft','halfshaft-rh',30),
('transmission-driveline','half-shafts-cv-joints','Inner CV joint','cv-inner',40),
('transmission-driveline','half-shafts-cv-joints','Outer CV joint','cv-outer',50),
('transmission-driveline','half-shafts-cv-joints','Boot & grease kit','cv-boot-kit',60),
('transmission-driveline','half-shafts-cv-joints','Complete half-shaft assy','halfshaft-complete',70),
('transmission-driveline','transfer-case-4wd','Transfer chain / belt','tc-chain',20),
('transmission-driveline','transfer-case-4wd','Actuator / motor','tc-actuator',30),
('transmission-driveline','transfer-case-4wd','Oil pump / gears internal','tc-internals',40),
('transmission-driveline','transfer-case-4wd','Housing & mounting','tc-housing',50),
('transmission-driveline','transfer-case-4wd','Complete transfer case','tc-complete',60),
-- Brakes --------------------------------------------------------------
('brakes','disc-brakes','Brake caliper (each corner)','disc-caliper',20),
('brakes','disc-brakes','Disc rotor / drum hybrid','disc-rotor',30),
('brakes','disc-brakes','Brake pads set','disc-pads',40),
('brakes','disc-brakes','Hardware & shims','disc-hardware',50),
('brakes','disc-brakes','Complete hub-to-hub corner','disc-corner-complete',60),
('brakes','drum-brakes','Wheel cylinder','drum-wheel-cylinder',20),
('brakes','drum-brakes','Brake shoes','drum-shoes',30),
('brakes','drum-brakes','Brake drum','drum-drum',40),
('brakes','drum-brakes','Adjuster & spring kit','drum-hardware-kit',50),
('brakes','drum-brakes','Complete drum assembly','drum-complete',60),
('brakes','parking-hand-brake','Cable LH','park-cable-lh',20),
('brakes','parking-hand-brake','Cable RH','park-cable-rh',30),
('brakes','parking-hand-brake','Pedal / lever assy','park-pedal-lever',40),
('brakes','parking-hand-brake','Electric actuator','park-actuator',50),
('brakes','parking-hand-brake','Complete parking brake system','park-complete',60),
('brakes','abs-electronic-brake','ABS pump & modulator','abs-pump',20),
('brakes','abs-electronic-brake','Wheel speed sensor','abs-wss',30),
('brakes','abs-electronic-brake','ABS / ESC control module','abs-module',40),
('brakes','abs-electronic-brake','Yaw / rate sensors','abs-yaw-sensors',50),
('brakes','abs-electronic-brake','Complete ABS set (as removed)','abs-set-complete',60),
('brakes','brake-lines-hoses','Hard brake lines','brake-hard-lines',20),
('brakes','brake-lines-hoses','Flexible hoses','brake-flex-hoses',30),
('brakes','brake-lines-hoses','Junction / combi valve','brake-junction',40),
('brakes','brake-lines-hoses','Bleed screws & clips','brake-line-hardware',50),
('brakes','brake-lines-hoses','Complete line kit (used)','brake-lines-complete',60),
('brakes','brake-servo-booster','Vacuum booster','servo-booster',20),
('brakes','brake-servo-booster','Brake master cylinder','brake-mc',30),
('brakes','brake-servo-booster','Fluid reservoir','brake-reservoir',40),
('brakes','brake-servo-booster','Vacuum pump (if fitted)','brake-vac-pump',50),
('brakes','brake-servo-booster','Boosted assembly complete','servo-mc-complete',60),
('brakes','hydraulic','Master cylinder (hydraulic)','hyd-master-cylinder',20),
('brakes','hydraulic','Wheel cylinders (drum)','hyd-wheel-cylinders',30),
('brakes','hydraulic','Proportioning / load valve','hyd-proportioning',40),
('brakes','hydraulic','Fluid reservoir & sensor','hyd-reservoir',50),
('brakes','hydraulic','Hydraulic line set','hyd-line-set',60);

INSERT INTO `epc_type_seed` (`cat_slug`, `sub_slug`, `name`, `slug`, `sort_order`) VALUES
-- Suspension & steering -----------------------------------------------
('suspension-steering','front-suspension','Control arms (front)','fs-control-arms',20),
('suspension-steering','front-suspension','Strut / shock (front)','fs-strut-shock',30),
('suspension-steering','front-suspension','Top mounts & bearings','fs-top-mounts',40),
('suspension-steering','front-suspension','Knuckle / spindle (front)','fs-knuckle',50),
('suspension-steering','front-suspension','Complete front corner assy','fs-corner-complete',60),
('suspension-steering','rear-suspension','Leaf / links (rear)','rs-links-leaf',20),
('suspension-steering','rear-suspension','Shock / damper (rear)','rs-shock',30),
('suspension-steering','rear-suspension','Coil springs (rear)','rs-springs',40),
('suspension-steering','rear-suspension','Trailing arm / beam','rs-trailing-arm',50),
('suspension-steering','rear-suspension','Complete rear axle assy','rs-complete',60),
('suspension-steering','shocks-springs','Coil spring (each)','ss-coil-spring',20),
('suspension-steering','shocks-springs','Gas shock / damper','ss-shock',30),
('suspension-steering','shocks-springs','Air spring / bag','ss-air-spring',40),
('suspension-steering','shocks-springs','Bump stops & dust kits','ss-bump-dust',50),
('suspension-steering','shocks-springs','Spring / shock set','ss-set',60),
('suspension-steering','steering-rack-gearbox','Steering rack','sr-rack',20),
('suspension-steering','steering-rack-gearbox','Pinion & housing','sr-pinion',30),
('suspension-steering','steering-rack-gearbox','Tie rod ends','sr-tie-rods',40),
('suspension-steering','steering-rack-gearbox','Rack boots & clamps','sr-boots',50),
('suspension-steering','steering-rack-gearbox','Complete steering rack','sr-rack-complete',60),
('suspension-steering','steering-column-shaft','Steering column','sc-column',20),
('suspension-steering','steering-column-shaft','Intermediate shaft','sc-intermediate',30),
('suspension-steering','steering-column-shaft','U-joints & coupler','sc-ujoints',40),
('suspension-steering','steering-column-shaft','Clock spring / Slip ring','sc-clock-spring',50),
('suspension-steering','steering-column-shaft','Column assy complete','sc-complete',60),
('suspension-steering','wheel-hubs-bearings','Wheel hub (front)','wh-hub-front',20),
('suspension-steering','wheel-hubs-bearings','Wheel hub (rear)','wh-hub-rear',30),
('suspension-steering','wheel-hubs-bearings','Wheel bearing kit','wh-bearing-kit',40),
('suspension-steering','wheel-hubs-bearings','ABS ring / encoder','wh-abs-ring',50),
('suspension-steering','wheel-hubs-bearings','Hub & bearing assy','wh-hub-assy',60),
('suspension-steering','anti-roll-bars-links','Anti-roll bar','arb-bar',20),
('suspension-steering','anti-roll-bars-links','Drop links','arb-drop-links',30),
('suspension-steering','anti-roll-bars-links','Bushings & brackets','arb-bushings',40),
('suspension-steering','anti-roll-bars-links','End links kit','arb-end-links',50),
('suspension-steering','anti-roll-bars-links','ARB complete','arb-complete',60),
-- Electrical & electronics -------------------------------------------
('electrical-electronics','battery-starting-circuits','Battery','bat-battery',20),
('electrical-electronics','battery-starting-circuits','Battery tray & hold-down','bat-tray',30),
('electrical-electronics','battery-starting-circuits','Starter relay / solenoid path','bat-starter-relay',40),
('electrical-electronics','battery-starting-circuits','Jump posts / terminals','bat-terminals',50),
('electrical-electronics','battery-starting-circuits','Main earth straps','bat-earth',60),
('electrical-electronics','charging-alternator','Alternator assy','chg-alternator',20),
('electrical-electronics','charging-alternator','Regulator (internal / ext)','chg-regulator',30),
('electrical-electronics','charging-alternator','Belt & tensioner (charging)','chg-belt',40),
('electrical-electronics','charging-alternator','Charging harness','chg-harness',50),
('electrical-electronics','charging-alternator','Complete charging set','chg-complete',60),
('electrical-electronics','exterior-lighting','Headlamp assy (each)','el-headlamp',20),
('electrical-electronics','exterior-lighting','Taillamp / stop lamp','el-taillamp',30),
('electrical-electronics','exterior-lighting','Fog / driving lamp','el-fog',40),
('electrical-electronics','exterior-lighting','Side repeater & bulbs','el-side',50),
('electrical-electronics','exterior-lighting','Lamp control module','el-lcm',60),
('electrical-electronics','interior-lighting','Dome / map lamps','il-dome',20),
('electrical-electronics','interior-lighting','Dash illumination','il-dash-illum',30),
('electrical-electronics','interior-lighting','Footwell / ambient','il-footwell',40),
('electrical-electronics','interior-lighting','Switch cluster (lights)','il-switch',50),
('electrical-electronics','interior-lighting','Interior harness section','il-harness',60),
('electrical-electronics','wiring-fuse-boxes','Fuse box / BCM housing','wf-fusebox',20),
('electrical-electronics','wiring-fuse-boxes','Relays & carriers','wf-relays',30),
('electrical-electronics','wiring-fuse-boxes','Main engine bay harness','wf-engine-harness',40),
('electrical-electronics','wiring-fuse-boxes','Interior cabin harness','wf-cabin-harness',50),
('electrical-electronics','wiring-fuse-boxes','Junction connectors','wf-junctions',60),
('electrical-electronics','sensors-actuators','Engine bay sensors','sa-engine',20),
('electrical-electronics','sensors-actuators','Chassis / brake sensors','sa-chassis',30),
('electrical-electronics','sensors-actuators','Climate sensors','sa-climate',40),
('electrical-electronics','sensors-actuators','Actuators (blend doors etc.)','sa-actuators',50),
('electrical-electronics','sensors-actuators','Sensor bundle (used)','sa-bundle',60),
('electrical-electronics','body-comfort-modules','BCM / body module','bc-bcm',20),
('electrical-electronics','body-comfort-modules','Door control module','bc-dcm',30),
('electrical-electronics','body-comfort-modules','Comfort / conven module','bc-comfort',40),
('electrical-electronics','body-comfort-modules','Window motors & regs (elec note)','bc-window-motors-note',50),
('electrical-electronics','body-comfort-modules','Module set (as removed)','bc-set',60),
('electrical-electronics','infotainment-displays','Head unit / radio','inf-headunit',20),
('electrical-electronics','infotainment-displays','Display / screen','inf-screen',30),
('electrical-electronics','infotainment-displays','Amplifier & speakers','inf-audio',40),
('electrical-electronics','infotainment-displays','Antenna & wiring','inf-antenna',50),
('electrical-electronics','infotainment-displays','Complete infotainment kit','inf-complete',60),
-- Fuel ----------------------------------------------------------------
('fuel-system','fuel-tank-sender','Fuel tank (metal / plastic)','ft-tank',20),
('fuel-system','fuel-tank-sender','Sender unit / pump basket','ft-sender',30),
('fuel-system','fuel-tank-sender','Filler neck & cap','ft-filler',40),
('fuel-system','fuel-tank-sender','Tank straps & shields','ft-straps',50),
('fuel-system','fuel-tank-sender','Tank assy complete','ft-complete',60),
('fuel-system','fuel-lines-rails','Rigid fuel lines','fl-rigid',20),
('fuel-system','fuel-lines-rails','Flexible high-pressure hoses','fl-flex-hp',30),
('fuel-system','fuel-lines-rails','Fuel rail & dampers','fl-rail',40),
('fuel-system','fuel-lines-rails','Quick connects & clips','fl-connectors',50),
('fuel-system','fuel-lines-rails','Line set (used)','fl-set',60),
('fuel-system','fuel-injection-induction','Injectors (petrol)','fi-injectors-petrol',20),
('fuel-system','fuel-injection-induction','Throttle body assy','fi-throttle',30),
('fuel-system','fuel-injection-induction','Intake plenum / manifold bits','fi-plenum',40),
('fuel-system','fuel-injection-induction','Fuel pressure regulator','fi-fpr',50),
('fuel-system','fuel-injection-induction','Induction complete (as removed)','fi-complete',60),
('fuel-system','fuel-pumps-filters','In-tank pump','fp-intank',20),
('fuel-system','fuel-pumps-filters','Inline / boost pump','fp-inline',30),
('fuel-system','fuel-pumps-filters','Fuel filter / housing','fp-filter',40),
('fuel-system','fuel-pumps-filters','Pump controller / relay','fp-control',50),
('fuel-system','fuel-pumps-filters','Pump kit complete','fp-complete',60),
('fuel-system','evap-emissions-fuel','Charcoal canister','ev-canister',20),
('fuel-system','evap-emissions-fuel','Purge valve','ev-purge',30),
('fuel-system','evap-emissions-fuel','Vent valve / LDP','ev-vent',40),
('fuel-system','evap-emissions-fuel','EVAP lines & clamps','ev-lines',50),
('fuel-system','evap-emissions-fuel','EVAP set complete','ev-complete',60),
-- Cooling & HVAC -----------------------------------------------------
('cooling-hvac','engine-cooling-radiator','Radiator core & tanks','ec-radiator',20),
('cooling-hvac','engine-cooling-radiator','Radiator fan & shroud','ec-fan',30),
('cooling-hvac','engine-cooling-radiator','Water pump','ec-water-pump',40),
('cooling-hvac','engine-cooling-radiator','Thermostat & housing','ec-thermostat',50),
('cooling-hvac','engine-cooling-radiator','Cooling hose set','ec-hoses',60),
('cooling-hvac','cabin-heating-cooling','Heater matrix / core','chc-matrix',20),
('cooling-hvac','cabin-heating-cooling','Heater box & doors','chc-heater-box',30),
('cooling-hvac','cabin-heating-cooling','Blower motor (heater)','chc-blower',40),
('cooling-hvac','cabin-heating-cooling','AC evaporator','chc-evap',50),
('cooling-hvac','cabin-heating-cooling','HVAC unit complete','chc-unit-complete',60),
('cooling-hvac','blower-ducts','Vent grilles & ducts','bd-ducts',20),
('cooling-hvac','blower-ducts','Resistor / speed controller','bd-resistor',30),
('cooling-hvac','blower-ducts','Cabin filters & covers','bd-filters',40),
('cooling-hvac','blower-ducts','Mode actuators','bd-actuators',50),
('cooling-hvac','blower-ducts','Duct set (used)','bd-set',60),
('cooling-hvac','ac-compressor-lines','AC compressor','ac-compressor',20),
('cooling-hvac','ac-compressor-lines','High / low pressure lines','ac-lines',30),
('cooling-hvac','ac-compressor-lines','Condenser & fans','ac-condenser',40),
('cooling-hvac','ac-compressor-lines','Receiver drier / TXV','ac-drier-valve',50),
('cooling-hvac','ac-compressor-lines','AC kit (as removed)','ac-kit',60),
-- Exhaust & emissions ------------------------------------------------
('exhaust-emissions','exhaust-manifolds-headers','Exhaust manifold','ex-manifold',20),
('exhaust-emissions','exhaust-manifolds-headers','Manifold gaskets & studs','ex-manifold-gaskets',30),
('exhaust-emissions','exhaust-manifolds-headers','Heat shield','ex-heat-shield',40),
('exhaust-emissions','exhaust-manifolds-headers','Turbo mount (on manif)','ex-turbo-mount',50),
('exhaust-emissions','exhaust-manifolds-headers','Manifold assy complete','ex-manifold-complete',60),
('exhaust-emissions','exhaust-pipes-silencers','Front pipe / flex','ex-front-pipe',20),
('exhaust-emissions','exhaust-pipes-silencers','Centre silencer','ex-centre-box',30),
('exhaust-emissions','exhaust-pipes-silencers','Rear silencer / tail','ex-rear-box',40),
('exhaust-emissions','exhaust-pipes-silencers','Hangers & rubbers','ex-hangers',50),
('exhaust-emissions','exhaust-pipes-silencers','Full exhaust line (used)','ex-line-full',60),
('exhaust-emissions','catalytic-converter-dpf','Catalytic converter','cat-converter',20),
('exhaust-emissions','catalytic-converter-dpf','DPF unit','cat-dpf',30),
('exhaust-emissions','catalytic-converter-dpf','DPF sensors / probes','cat-dpf-sensors',40),
('exhaust-emissions','catalytic-converter-dpf','Mounting brackets','cat-brackets',50),
('exhaust-emissions','catalytic-converter-dpf','Cat/DPF assy complete','cat-complete',60),
('exhaust-emissions','egr-emission-valves','EGR valve','egr-valve',20),
('exhaust-emissions','egr-emission-valves','EGR cooler','egr-cooler',30),
('exhaust-emissions','egr-emission-valves','Secondary air pump','egr-air-pump',40),
('exhaust-emissions','egr-emission-valves','Vacuum solenoids','egr-solenoids',50),
('exhaust-emissions','egr-emission-valves','Emission valve set','egr-set',60),
('exhaust-emissions','oxygen-exhaust-sensors','O2 / lambda sensor','oxy-lambda',20),
('exhaust-emissions','oxygen-exhaust-sensors','NOx / particulate sensor','oxy-nox-part',30),
('exhaust-emissions','oxygen-exhaust-sensors','Exhaust temp sensor','oxy-temp',40),
('exhaust-emissions','oxygen-exhaust-sensors','Sensor harness stubs','oxy-harness',50),
('exhaust-emissions','oxygen-exhaust-sensors','Sensor bundle','oxy-bundle',60),
-- Body (incl. seed exterior) ----------------------------------------
('body','bumpers-grilles','Front bumper cover','bg-front-cover',20),
('body','bumpers-grilles','Rear bumper cover','bg-rear-cover',30),
('body','bumpers-grilles','Grille & surrounds','bg-grille',40),
('body','bumpers-grilles','Fog lamp bezels','bg-fog-bezel',50),
('body','bumpers-grilles','Bumper reinforcement / beam','bg-beam',60),
('body','glass-mirrors','Windscreen','gm-windscreen',20),
('body','glass-mirrors','Door glass (each)','gm-door-glass',30),
('body','glass-mirrors','Rear quarter / vent glass','gm-quarter',40),
('body','glass-mirrors','Mirror assy (each)','gm-mirror',50),
('body','glass-mirrors','Glass & mirror set','gm-set',60),
('body','doors-tailgate','Door shell','door-shell',20),
('body','doors-tailgate','Door handle (inner / outer)','door-handle',30),
('body','doors-tailgate','Door lock','door-lock',40),
('body','doors-tailgate','Window regulator','window-regulator',50),
('body','doors-tailgate','Door glass','door-glass',60),
('body','doors-tailgate','Door hinges','door-hinges',70),
('body','doors-tailgate','Door seal','door-seal',80),
('body','roof-cab-structure','Roof panel / top','rc-roof-panel',20),
('body','roof-cab-structure','Pillars & stiffeners','rc-pillars',30),
('body','roof-cab-structure','Sunroof cassette','rc-sunroof',40),
('body','roof-cab-structure','Rain gutters & trims','rc-gutters',50),
('body','roof-cab-structure','Cab structure assy','rc-structure',60),
('body','panels-outer-skin','Guard / fender (each)','ps-fender',20),
('body','panels-outer-skin','Bonnet / hood','ps-bonnet',30),
('body','panels-outer-skin','Tailgate / boot lid','ps-tailgate',40),
('body','panels-outer-skin','Quarter panel','ps-quarter',50),
('body','panels-outer-skin','Floor & inner panels','ps-inner-floor',60),
('body','trims-badges-mouldings','Side mouldings & rub strips','tb-mouldings',20),
('body','trims-badges-mouldings','Badges & emblems','tb-badges',30),
('body','trims-badges-mouldings','Wheel arch trims','tb-arch',40),
('body','trims-badges-mouldings','Window surround chrome','tb-window-surround',50),
('body','trims-badges-mouldings','Trim set bundle','tb-set',60),
('body','weatherstrips-seals','Door aperture seals','ws-door-seals',20),
('body','weatherstrips-seals','Glass run channels','ws-glass-run',30),
('body','weatherstrips-seals','Bonnet / boot seals','ws-bonnet-boot',40),
('body','weatherstrips-seals','Firewall / bulkhead seals','ws-firewall',50),
('body','weatherstrips-seals','Seal kit (used)','ws-kit',60),
('body','exterior','Front panels & wings','ext-front-panels',20),
('body','exterior','Rear panels & quarters','ext-rear-panels',30),
('body','exterior','Roof & rain gutters','ext-roof',40),
('body','exterior','Brightwork & chrome','ext-brightwork',50),
('body','exterior','Exterior hardware set','ext-set',60),
-- Interior -----------------------------------------------------------
('interior','seats-belts','Front seat (LH)','sb-seat-fl',20),
('interior','seats-belts','Front seat (RH)','sb-seat-fr',30),
('interior','seats-belts','Rear seat bench','sb-rear-bench',40),
('interior','seats-belts','Seat belts & buckles','sb-belts',50),
('interior','seats-belts','Seat rails & motors','sb-rails',60),
('interior','dashboard-instruments','Instrument cluster','db-cluster',20),
('interior','dashboard-instruments','Dashboard top & trim','db-top',30),
('interior','dashboard-instruments','Centre stack trim','db-stack',40),
('interior','dashboard-instruments','Glovebox & ashtray','db-glovebox',50),
('interior','dashboard-instruments','Dash harness & switches','db-harness',60),
('interior','steering-wheel-airbag','Steering wheel','sw-wheel',20),
('interior','steering-wheel-airbag','Airbag (wheel)','sw-airbag',30),
('interior','steering-wheel-airbag','Clock spring (interior side)','sw-clockspring',40),
('interior','steering-wheel-airbag','Paddle shift / controls','sw-paddles',50),
('interior','steering-wheel-airbag','Wheel assy complete','sw-complete',60),
('interior','door-cards-pillar-trim','Door card (each)','dc-card',20),
('interior','door-cards-pillar-trim','Pillar trims A/B/C','dc-pillars',30),
('interior','door-cards-pillar-trim','Armrest & pulls','dc-armrest',40),
('interior','door-cards-pillar-trim','Speaker grilles (door)','dc-speaker-grille',50),
('interior','door-cards-pillar-trim','Trim set','dc-set',60),
('interior','floor-carpets','Front floor carpets','fc-front',20),
('interior','floor-carpets','Rear floor carpets','fc-rear',30),
('interior','floor-carpets','Underfelt & sound deadening','fc-deadening',40),
('interior','floor-carpets','Pedal trims & dead pedal','fc-pedals',50),
('interior','floor-carpets','Carpet set','fc-set',60),
('interior','headlining-parcel-shelf','Headlining board','hp-headlining',20),
('interior','headlining-parcel-shelf','Sun visors & clips','hp-visors',30),
('interior','headlining-parcel-shelf','Parcel shelf / tonneau','hp-parcel',40),
('interior','headlining-parcel-shelf','Interior light pods','hp-lights',50),
('interior','headlining-parcel-shelf','Roof liner set','hp-set',60),
('interior','console-storage','Centre console','cs-console',20),
('interior','console-storage','Cup holders & lids','cs-cups',30),
('interior','console-storage','Armrest storage','cs-armrest',40),
('interior','console-storage','12V / USB panels','cs-power',50),
('interior','console-storage','Console assy complete','cs-complete',60),
-- Wheels & tyres -----------------------------------------------------
('wheels-tyres','road-wheels-caps','Steel wheel (each)','rw-steel',20),
('wheels-tyres','road-wheels-caps','Alloy wheel (each)','rw-alloy',30),
('wheels-tyres','road-wheels-caps','Space-saver spare','rw-space-saver',40),
('wheels-tyres','road-wheels-caps','Centre caps & trims','rw-caps',50),
('wheels-tyres','road-wheels-caps','Wheel set (4)','rw-set-4',60),
('wheels-tyres','tyres','Tyre (each)','ty-tyre',20),
('wheels-tyres','tyres','Run-flat tyre','ty-runflat',30),
('wheels-tyres','tyres','Tyre set (pair)','ty-pair',40),
('wheels-tyres','tyres','Tyre set (4)','ty-set-4',50),
('wheels-tyres','tyres','Tyre pressure parts','ty-tpm-parts',60),
('wheels-tyres','tpms-valves','TPMS sensor (each)','tpms-sensor',20),
('wheels-tyres','tpms-valves','Rubber valve stems','tpms-valve',30),
('wheels-tyres','tpms-valves','TPMS controller / receiver','tpms-controller',40),
('wheels-tyres','tpms-valves','Calibration tool (if car)','tpms-tool',50),
('wheels-tyres','tpms-valves','TPMS kit','tpms-kit',60),
('wheels-tyres','wheel-fasteners-locks','Wheel bolts / nuts set','wf-bolts',20),
('wheels-tyres','wheel-fasteners-locks','Locking wheel nuts & key','wf-locking',30),
('wheels-tyres','wheel-fasteners-locks','Spacers & adaptors','wf-spacers',40),
('wheels-tyres','wheel-fasteners-locks','Stud conversion kit','wf-studs',50),
('wheels-tyres','wheel-fasteners-locks','Fastener bundle','wf-bundle',60),
-- Accessories & consumables ------------------------------------------
('accessories-consumables','wipers-washers','Wiper arms (pair)','ww-arms',20),
('accessories-consumables','wipers-washers','Wiper blades','ww-blades',30),
('accessories-consumables','wipers-washers','Wiper motor & linkage','ww-motor',40),
('accessories-consumables','wipers-washers','Washer bottle & pump','ww-washer',50),
('accessories-consumables','wipers-washers','Washer jets & hoses','ww-jets',60),
('accessories-consumables','filters-service','Oil filter','fil-oil',20),
('accessories-consumables','filters-service','Air filter','fil-air',30),
('accessories-consumables','filters-service','Cabin / pollen filter','fil-cabin',40),
('accessories-consumables','filters-service','Fuel filter','fil-fuel',50),
('accessories-consumables','filters-service','Filter service kit','fil-kit',60),
('accessories-consumables','auxiliary-belts','Serpentine / fan belt','ab-serpentine',20),
('accessories-consumables','auxiliary-belts','AC compressor belt','ab-ac',30),
('accessories-consumables','auxiliary-belts','Tensioner & idler pulleys','ab-tensioner',40),
('accessories-consumables','auxiliary-belts','Belt kit complete','ab-kit',50),
('accessories-consumables','auxiliary-belts','Timing belt (service spare)','ab-timing-belt-spare',60),
('accessories-consumables','fluids-caps-sundries','Service fluids (as bottled)','flud-bottles',20),
('accessories-consumables','fluids-caps-sundries','Oil caps & dipsticks','flud-caps',30),
('accessories-consumables','fluids-caps-sundries','Coolant caps & tanks','flud-cool-cap',40),
('accessories-consumables','fluids-caps-sundries','Brake fluid reservoir cap','flud-brake-cap',50),
('accessories-consumables','fluids-caps-sundries','Sundries bundle','flud-bundle',60),
('accessories-consumables','jack-emergency-tools','Scissor / bottle jack','je-jack',20),
('accessories-consumables','jack-emergency-tools','Wheel brace / spanner','je-spanner',30),
('accessories-consumables','jack-emergency-tools','Towing eye & foam','je-tow-eye',40),
('accessories-consumables','jack-emergency-tools','Triangle & vest','je-safety',50),
('accessories-consumables','jack-emergency-tools','Tool roll complete','je-tool-roll',60);

INSERT INTO `epc_types` (`subcategory_id`, `name`, `slug`, `sort_order`)
SELECT sc.`id`, s.`name`, s.`slug`, s.`sort_order`
FROM `epc_type_seed` s
INNER JOIN `epc_categories` c
  ON c.`slug` = s.`cat_slug` AND c.`is_active` = 1
INNER JOIN `epc_subcategories` sc
  ON sc.`category_id` = c.`id` AND sc.`slug` = s.`sub_slug` AND sc.`is_active` = 1
ON DUPLICATE KEY UPDATE
  `name`       = VALUES(`name`),
  `sort_order` = VALUES(`sort_order`);

DROP TEMPORARY TABLE IF EXISTS `epc_type_seed`;

-- Next: run `02d_epc_spine_step3.sql` then optional `02e_epc_variants_dismantler.sql`.
